### ISSUE TITLE
Deployment paused

### ISSUE THREAD

**Issue by llakala** [crllect/Cryphr#24]
See the image for how the site looks on visit.
![Screenshot 2024-05-31 8 57 01 AM](https://github.com/crllect/Cryphr/assets/78693624/07cb915c-aca0-405e-b59f-89bf8803c6c8)

**Comment by crllect** [comment]
As of right now, this is intentional. Vercel has gotten pretty expensive so it will be down for a couple days until I move the bare server to a different hosting service

**Comment by GarethFlandro** [comment]
Imagine making a proxy so popular that Vercel booted you off the free version lol

**Comment by Mazedotexe** [comment]
> Imagine making a proxy so popular that Vercel booted you off the free version lol

yeah, 17000 users is a lot

**Comment by llakala** [comment]
> > Imagine making a proxy so popular that Vercel booted you off the free version lol
> 
> yeah, 17000 users is a lot

17 THOUSAND? I need to start making more bug reports, it'd be a public service at this point.

**Comment by GarethFlandro** [comment]
that's github for you

**Comment by crllect** [comment]
![image](https://github.com/crllect/Cryphr/assets/144494583/1d24c020-1ed9-435b-a320-dae3ca973c38)

**Comment by GarethFlandro** [comment]
does that mean active users or searches

**Comment by crllect** [comment]
Alright, its back up I hope

**Comment by GarethFlandro** [comment]
It works!
